Delegate all launcher methods.
I observed several strange SSH launch failer that seems tricky to investigate:

        <===[JENKINS REMOTING CAPACITY]===>channel started
        Slave.jar version: 2.47
        This is a Unix slave
        Slave successfully connected and online
        channel stopped
        Connection terminated

Log says:

        Mar 24, 2016 9:53:47 AM jenkins.plugins.openstack.compute.JCloudsCloud ensureLaunched
        WARNING: Error while launching slave: XXX
        java.util.concurrent.ExecutionException: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
	        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        	at java.util.concurrent.FutureTask.get(FutureTask.java:202)
        	at jenkins.plugins.openstack.compute.JCloudsCloud.ensureLaunched(JCloudsCloud.java:239)
	        at jenkins.plugins.openstack.compute.JCloudsCloud.access$200(JCloudsCloud.java:55)
        	at jenkins.plugins.openstack.compute.JCloudsCloud$1.call(JCloudsCloud.java:218)
	        at jenkins.plugins.openstack.compute.JCloudsCloud$1.call(JCloudsCloud.java:201)
        	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        	at java.lang.Thread.run(Thread.java:745)
        Caused by: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
	        at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:254)
        	... 5 more

I presume the launcher will be able to investigate better.